=== AbhinavrnairCu-20/wtswo/SWO.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xs:element name="SWO">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Student">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="Committee" type="xs:string"/>
            <xs:element name="Class" type="xs:string"/>
            <xs:element name="Stipend" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Faculty">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Designation" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== AbhinavrnairCu-20/wtswo/SWO.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SWO.xsl"?>
<SWO xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="SWO.xsd">
<Student>
    <Name>Deepak Raj</Name>
    <Committee>Overall Head</Committee>
    <Class>BSc CME</Class>
    <Stipend>10000</Stipend>
</Student>
<Faculty>
    <Name>Father Lijo Thomas</Name>
    <Designation>Director </Designation>
</Faculty>

<Student>
    <Name>Dheenabandhan S</Name>
    <Committee>Audi </Committee>
    <Class>BCom Honours</Class>
    <Stipend>9000</Stipend>
</Student>
<Faculty>
    <Name>Mr Purnananda Bhaskar G</Name>
    <Designation>Student Welfare Officer</Designation>
</Faculty>

<Student>
    <Name>Rahul S</Name>
    <Committee>Media</Committee>
    <Class>BCom Honours</Class>
    <Stipend>9000</Stipend>
</Student>
<Faculty>
    <Name>Mr Donald Paul</Name>
    <Designation>Asst. Student Welfare Officer</Designation>
</Faculty>

<Student>
    <Name>Anjali Balakrishnan</Name>
    <Committee>Hospitality</Committee>
    <Class>BSc BCB</Class>
    <Stipend>9000</Stipend>
</Student>
<Faculty>
    <Name>Mr Prabin V</Name>
    <Designation>Dance Co- ordinator</Designation>
</Faculty>

<Student>
    <Name>Dhanin Gupta</Name>
    <Committee>Art </Committee>
    <Class>BSc CME</Class>
    <Stipend>6000</Stipend>
</Student>
<Faculty>
    <Name>Ms. Anna Reshmy</Name>
    <Designation>Co-ordinator SWO NCR</Designation>
</Faculty>

<Student>
    <Name>Sumana Sainath</Name>
    <Committee>Creative</Committee>
    <Class>BSc PME</Class>
    <Stipend>8000</Stipend>
</Student>
<Faculty>
    <Name>Bhavishya Sajith</Name>
    <Designation>Co-ordinator SWO Lavasa </Designation>
</Faculty>

</SWO>
